<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Away_homeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = date('Y-m-d');

        DB::table('away_home')->insert([
            [
                'convention_no' => 'RAL-E5th',
                'league_name' => 'RAL-1',
                'game_date' => '2021/01/01',
                'sort' => 1,
                'home_team' => 'team-A',
                'away_team' => 'team-D',
                'total_goal' => null,
                'player1' => null,
                'player2' => null,
                'player3' => null,
                'player4' => null,
                'player5' => null,
                'player6' => null,
                'player7' => null,
                'player8' => null,
                'player9' => null,
                'player10' => null,
                'goal1' => null,
                'goal2' => null,
                'goal3' => null,
                'goal4' => null,
                'goal5' => null,
                'goal6' => null,
                'goal7' => null,
                'goal8' => null,
                'goal9' => null,
                'goal10' => null,
                'assist1' => null,
                'assist2' => null,
                'assist3' => null,
                'assist4' => null,
                'assist5' => null,
                'assist6' => null,
                'assist7' => null,
                'assist8' => null,
                'assist9' => null,
                'assist10' => null,
                'as1' => null,
                'as2' => null,
                'as3' => null,
                'as4' => null,
                'as5' => null,
                'as6' => null,
                'as7' => null,
                'as8' => null,
                'as9' => null,
                'as10' => null,
                'created_at' => '2021/01/01 11:11:11',
            ],
            [
                'convention_no' => 'RAL-E5th',
                'league_name' => 'RAL-1',
                'game_date' => '2021/01/01',
                'sort' => 1,
                'home_team' => 'team-A',
                'away_team' => 'team-D',
                'total_goal' => null,
                'player1' => null,
                'player2' => null,
                'player3' => null,
                'player4' => null,
                'player5' => null,
                'player6' => null,
                'player7' => null,
                'player8' => null,
                'player9' => null,
                'player10' => null,
                'goal1' => null,
                'goal2' => null,
                'goal3' => null,
                'goal4' => null,
                'goal5' => null,
                'goal6' => null,
                'goal7' => null,
                'goal8' => null,
                'goal9' => null,
                'goal10' => null,
                'assist1' => null,
                'assist2' => null,
                'assist3' => null,
                'assist4' => null,
                'assist5' => null,
                'assist6' => null,
                'assist7' => null,
                'assist8' => null,
                'assist9' => null,
                'assist10' => null,
                'as1' => null,
                'as2' => null,
                'as3' => null,
                'as4' => null,
                'as5' => null,
                'as6' => null,
                'as7' => null,
                'as8' => null,
                'as9' => null,
                'as10' => null,
                'created_at' => '2021/01/01 11:11:11',
            ],
            [
                'convention_no' => 'RAL-E5th',
                'league_name' => 'RAL-1',
                'game_date' => '2021/01/01',
                'sort' => 4,
                'home_team' => 'team-D',
                'away_team' => 'team-A',
                'total_goal' => null,
                'player1' => null,
                'player2' => null,
                'player3' => null,
                'player4' => null,
                'player5' => null,
                'player6' => null,
                'player7' => null,
                'player8' => null,
                'player9' => null,
                'player10' => null,
                'goal1' => null,
                'goal2' => null,
                'goal3' => null,
                'goal4' => null,
                'goal5' => null,
                'goal6' => null,
                'goal7' => null,
                'goal8' => null,
                'goal9' => null,
                'goal10' => null,
                'assist1' => null,
                'assist2' => null,
                'assist3' => null,
                'assist4' => null,
                'assist5' => null,
                'assist6' => null,
                'assist7' => null,
                'assist8' => null,
                'assist9' => null,
                'assist10' => null,
                'as1' => null,
                'as2' => null,
                'as3' => null,
                'as4' => null,
                'as5' => null,
                'as6' => null,
                'as7' => null,
                'as8' => null,
                'as9' => null,
                'as10' => null,
                'created_at' => '2021/01/01 11:11:11',
            ],
            [
                'convention_no' => 'RAL-E5th',
                'league_name' => 'RAL-1',
                'game_date' => '2021/01/01',
                'sort' => 2,
                'home_team' => 'team-B',
                'away_team' => 'team-D',
                'total_goal' => null,
                'player1' => null,
                'player2' => null,
                'player3' => null,
                'player4' => null,
                'player5' => null,
                'player6' => null,
                'player7' => null,
                'player8' => null,
                'player9' => null,
                'player10' => null,
                'goal1' => null,
                'goal2' => null,
                'goal3' => null,
                'goal4' => null,
                'goal5' => null,
                'goal6' => null,
                'goal7' => null,
                'goal8' => null,
                'goal9' => null,
                'goal10' => null,
                'assist1' => null,
                'assist2' => null,
                'assist3' => null,
                'assist4' => null,
                'assist5' => null,
                'assist6' => null,
                'assist7' => null,
                'assist8' => null,
                'assist9' => null,
                'assist10' => null,
                'as1' => null,
                'as2' => null,
                'as3' => null,
                'as4' => null,
                'as5' => null,
                'as6' => null,
                'as7' => null,
                'as8' => null,
                'as9' => null,
                'as10' => null,
                'created_at' => '2021/01/01 11:11:11',
            ],
            [
                'convention_no' => 'RAL-E5th',
                'league_name' => 'RAL-1',
                'game_date' => '2021/01/01',
                'sort' => 2,
                'home_team' => 'team-A',
                'away_team' => 'team-B',
                'total_goal' => null,
                'player1' => null,
                'player2' => null,
                'player3' => null,
                'player4' => null,
                'player5' => null,
                'player6' => null,
                'player7' => null,
                'player8' => null,
                'player9' => null,
                'player10' => null,
                'goal1' => null,
                'goal2' => null,
                'goal3' => null,
                'goal4' => null,
                'goal5' => null,
                'goal6' => null,
                'goal7' => null,
                'goal8' => null,
                'goal9' => null,
                'goal10' => null,
                'assist1' => null,
                'assist2' => null,
                'assist3' => null,
                'assist4' => null,
                'assist5' => null,
                'assist6' => null,
                'assist7' => null,
                'assist8' => null,
                'assist9' => null,
                'assist10' => null,
                'as1' => null,
                'as2' => null,
                'as3' => null,
                'as4' => null,
                'as5' => null,
                'as6' => null,
                'as7' => null,
                'as8' => null,
                'as9' => null,
                'as10' => null,
                'created_at' => '2021/01/01 11:11:11',
            ],
            [
                'convention_no' => 'RAL-E5th',
                'league_name' => 'RAL-1',
                'game_date' => '2021/01/01',
                'sort' => 3,
                'home_team' => 'team-C',
                'away_team' => 'team-D',
                'total_goal' => null,
                'player1' => null,
                'player2' => null,
                'player3' => null,
                'player4' => null,
                'player5' => null,
                'player6' => null,
                'player7' => null,
                'player8' => null,
                'player9' => null,
                'player10' => null,
                'goal1' => null,
                'goal2' => null,
                'goal3' => null,
                'goal4' => null,
                'goal5' => null,
                'goal6' => null,
                'goal7' => null,
                'goal8' => null,
                'goal9' => null,
                'goal10' => null,
                'assist1' => null,
                'assist2' => null,
                'assist3' => null,
                'assist4' => null,
                'assist5' => null,
                'assist6' => null,
                'assist7' => null,
                'assist8' => null,
                'assist9' => null,
                'assist10' => null,
                'as1' => null,
                'as2' => null,
                'as3' => null,
                'as4' => null,
                'as5' => null,
                'as6' => null,
                'as7' => null,
                'as8' => null,
                'as9' => null,
                'as10' => null,
                'created_at' => '2021/01/01 11:11:11',
            ],

        ]);
    }
}
